### ISSUE TITLE
Expose pre-commit hook?

### ISSUE THREAD

**Issue by sloria** [4Catalyzer/alembic-autogen-check#3]

**Comment by itajaja** [comment]
[isn't there one already?](https://github.com/4Catalyzer/alembic-autogen-check/blob/master/.pre-commit-config.yaml)

**Comment by sloria** [comment]
I mean "expose a hook" to users so you could do something like

```yaml
repos:
- repo: https://github.com/4Catalyzer/alembic-autogen-check
  rev: master
  hooks:
  - id: alembic-autogen-check
```
